### ISSUE TITLE
storage/prefixの割り当てルール

### ISSUE THREAD

**Issue by shibafu528** [shibafu528/dtvault#3]
以下のそれぞれについて、ユーザが書いたルールに基づいて決定して自動振り分けできるようにする。

1. 保存先ストレージ
2. prefix (ストレージルートディレクトリ以下の相対パスと思ってもらえれば)

イメージしているのはメーラーのフィルタ機能みたいな感じ。  
将来的に複雑な条件式とか書けたらすごいけど、最初は単純で良いかと。

**Comment by shibafu528** [comment]
## Spec
* ルールはストレージ用、prefix用があり、それぞれ複数個記述できる。
* 一番最初に全ての条件を満たしたルールが適用される。
* ストレージルールが1つもヒットしなかった場合は、一番最初に定義されたストレージに保存される
  * いずれ、デフォルトストレージのフラグを付与できるようにしたほうが良いと考えている
* prefixルールが1つもヒットしなかった場合は、prefixは空になる

## Example
```toml
[[storage_rules]]
storage_label = "alpha"
  [storage_rules.condition]
  # Program.name に "感動ドキュメンタリー" が含まれていて、かつ Program.description に "一同涙" が含まれている
  # 番組を、label "alpha" のストレージに保存する
  title = "感動ドキュメンタリー"
  description = "一同涙"

[[storage_rules]]
storage_label = "bravo"
  [storage_rules.condition]
  # 2021年1月1日〜2021年12月31日の番組を、label "bravo" のストレージに保存する
  # .. と ... があるが、Rubyのそれと同じ
  start_at = "2021-01-01 00:00...2022-01-01 00:00"

[[storage_rules]]
# storage_label, storage_idはどちらか一方のみ指定できる
storage_id = "00000000-0000-0000-0000-000000000000"

[[prefix_rules]]
prefix = "GR/2021Q1"
  [storage_rules.condition]
  # 2021年1月1日〜2021年3月31日に放送された地上波の番組を "GR/2021Q1" に保存する
  start_at = "2021-01-01 00:00...2021-04-01 00:00"
  channel_type = "GR"
```
